export const API__GET = "API__GET";

export const HOME__ENTER = "HOME__ENTER";
export const HOME__LEAVE = "HOME__LEAVE";
export const HOME__SUBMIT = "HOME__SUBMIT";
export const HOME__SET_DEPARTURE_IATA = "HOME__SET_DEPARTURE_IATA";
export const HOME__SET_DESTINATION_IATA = "HOME__SET_DESTINATION_IATA";
export const HOME__SET_DEPARTURE_DATE = "HOME__SET_DEPARTURE_DATE";
export const HOME__SET_ARRIVAL_DATE = "HOME__SET_ARRIVAL_DATE";

export const STATIONS__LOAD = "STATIONS__LOAD";
