export const API__GET = "API__GET";

export const HOME__ENTER = "HOME__ENTER";
export const HOME__LEAVE = "HOME__LEAVE";
export const HOME__SUBMIT = "HOME__SUBMIT";
export const HOME__SET_DEPARTURE_IATA = "HOME__SET_DEPARTURE_IATA";
export const HOME__SET_DESTINATION_IATA = "HOME__SET_DESTINATION_IATA";
export const HOME__SET_DEPARTURE_DATE = "HOME__SET_DEPARTURE_DATE";
export const HOME__SET_RETURN_DATE = "HOME__SET_RETURN_DATE";

export const SELECT_FLIGHT__ENTER = "SELECT_FLIGHT__ENTER";
export const SELECT_FLIGHT__LEAVE = "SELECT_FLIGHT__LEAVE";
export const SELECT_FLIGHT__SET_DEPARTURE_DATE =
  "SELECT_FLIGHT__SET_DEPARTURE_DATE";
export const SELECT_FLIGHT__SET_RETURN_DATE = "SELECT_FLIGHT__SET_RETURN_DATE";
export const SELECT_FLIGHT__SET_SELECTED_OUTBOUND_FLIGHT =
  "SELECT_FLIGHT__SET_SELECTED_OUTBOUND_FLIGHT";
export const SELECT_FLIGHT__SET_SELECTED_INBOUND_FLIGHT =
  "SELECT_FLIGHT__SET_SELECTED_INBOUND_FLIGHT";
export const SELECT_FLIGHT__SUBMIT = "SELECT_FLIGHT__SUBMIT";
export const SELECT_FLIGHT__CLOSE_MODAL = "SELECT_FLIGHT__CLOSE_MODAL";

export const STATIONS__LOAD = "STATIONS__LOAD";
