export const HOME__SET_FIELDS = "HOME__SET_FIELDS";
export const HOME__SET_ERROR = "HOME__SET_ERROR";
export const HOME__RESET_ERRORS = "HOME__RESET_ERRORS";
export const HOME__RESET = "HOME__RESET";

export const STATIONS__LOAD_START = "STATIONS__LOAD_START";
export const STATIONS__LOAD_SUCCESS = "STATIONS__LOAD_SUCCESS";
export const STATIONS__LOAD_FAILURE = "STATIONS__LOAD_FAILURE";
